const API_BASE='http://127.0.0.1:8000';
let DATA, routeData, currentCampusId='namseoul', map, graphLayer, routeLayer, start, end, clicks=0, reviewMap, reviewLayer, reviewDrawing=false, reviewPoints=[], reviewAdded=[], reviewRemoved=[];
const $=s=>document.querySelector(s);
fetch('data.json').then(r=>r.json()).then(data=>{DATA=data;routeData=data;document.querySelector('#sampleId').textContent=data.sample_id;initCompare();initRoute()});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='route'&&map)setTimeout(()=>map.invalidateSize(),50);if(b.dataset.tab==='review'){initReview();setTimeout(()=>reviewMap.invalidateSize(),50)}});
function initCompare(){ $('#edgeMetric').textContent=DATA.edges.length;const sec=DATA.training_metrics.seconds;$('#timeMetric').textContent=sec==null?'미기록':(sec<60?`${sec}초`:`${Math.floor(sec/60)}분 ${Math.round(sec%60)}초`);initBeforeAfter();renderStep(0); renderChart(); document.querySelectorAll('.step').forEach(b=>b.onclick=()=>{document.querySelectorAll('.step').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderStep(+b.dataset.step)}) }
function initBeforeAfter(){const section=document.createElement('section');section.className='before-after';section.innerHTML=`<div class="section-heading"><div><p class="eyebrow">SAME SAMPLE · BEFORE / AFTER</p><h3>학습 전·후 예측 결과 비교</h3><p>동일한 입력 이미지 <strong>${DATA.sample_id}</strong>에 대해 학습 전 랜덤 초기화 모델과 학습 완료 U-Net의 예측을 비교합니다.</p></div><span class="pill green">실제 파일 비교</span></div><div class="before-after-grid"><article><div class="card-top"><span>학습 전 예측</span><span class="pill">RANDOM INIT</span></div><img src="../nsu_real_dataset/demo_before_overlay.png" alt="학습 전 예측 결과"><p>가중치를 학습하지 않은 U-Net의 예측입니다. 보행 패턴을 학습하지 않아 노이즈가 많습니다.</p></article><article><div class="card-top"><span>학습 후 예측</span><span class="pill green">TRAINED U-NET</span></div><img src="../nsu_real_dataset/demo_after_overlay.png" alt="학습 후 예측 결과"><p>동일 샘플에 10 epoch 학습된 모델을 적용한 결과입니다.</p></article></div><div class="comparison-note">비교 기준: 같은 입력 이미지 · 같은 임계값 0.3 · 같은 U-Net 구조 · 학습 전은 고정된 랜덤 초기화 · 학습 후는 <code>unet_nsu_walkable.pt</code></div>`;document.querySelector('.pipeline-title').before(section)}
function renderStep(i){const step=DATA.steps[Math.min(i,2)];$('#stepTitle').textContent=i===3?'4. 그래프 데이터':step.title;$('#stepText').textContent=i===3?'OSM 보행 그래프를 서비스용 노드·간선으로 연결합니다. 현재 길찾기는 이 그래프를 사용합니다.':step.text;$('#stepDetail').textContent=i===3?'수집: OSM 보행로 LineString을 노드와 간선으로 변환합니다.\n노드: 교차점·끝점·분기점 역할을 하는 좌표입니다.\n간선: 두 노드를 연결하는 보행로이며 거리와 highway 태그를 가집니다.\n서비스: 지도 클릭 위치를 가장 가까운 노드에 연결하고 최단경로를 계산합니다.\n현재 상태: 서비스 그래프는 OSM 기반이며, 다음 단계에서 AI 예측 마스크 기반 그래프로 교체합니다.':step.detail;const v=$('#stepVisual');if(i===3){v.innerHTML='<div style="padding:25px;text-align:center"><div style="font-size:48px">🗺️</div><strong>'+DATA.nodes.length+' nodes · '+DATA.edges.length+' edges</strong><p style="margin-top:10px;color:#68778c">길찾기 서비스 탭에서 직접 경로를 선택해보세요.</p></div>'}else{v.innerHTML='<img src="'+step.image+'">'}}
function renderChart(){const max=Math.max(...DATA.training.loss);$('#lossChart').innerHTML=DATA.training.loss.map((v,i)=>`<div class="bar" style="height:${Math.max(12,100*v/max)}%"><span>${i+1}</span></div>`).join('')}
function initRoute(){map=L.map('map').setView(routeData.center,routeData.zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);graphLayer=L.layerGroup().addTo(map);drawRouteGraph();map.on('click',e=>choose(e.latlng));$('#resetBtn').onclick=reset;initCampusSelector()}
function drawRouteGraph(){graphLayer.clearLayers();routeData.edges.forEach(e=>L.polyline(e.coords.map(c=>[c[1],c[0]]),{color:'#b9c4d5',weight:3,opacity:.8}).addTo(graphLayer))}
async function initCampusSelector(){const mode=document.querySelector('#route .mode');const label=document.createElement('label');label.className='campus-picker';label.innerHTML='<span>캠퍼스</span><select id="campusSelect" aria-label="캠퍼스 선택"></select>';mode.before(label);const select=label.querySelector('select');try{const response=await fetch(API_BASE+'/api/campuses');if(!response.ok)throw new Error('campus api unavailable');const campuses=await response.json();campuses.forEach(c=>select.add(new Option(c.name,c.campus_id)));}catch(error){select.add(new Option('남서울대학교 천안 캠퍼스','namseoul'));select.add(new Option('서울대학교 관악 캠퍼스','snu-gwanak'));}select.value=currentCampusId;select.onchange=()=>switchCampus(select.value)}
async function switchCampus(campusId){const urls={namseoul:'data.json','snu-gwanak':'../data/snu_gwanak.json'};try{const response=await fetch(urls[campusId]);if(!response.ok)throw new Error('campus data unavailable');routeData=await response.json();currentCampusId=campusId;map.setView(routeData.center,routeData.zoom);drawRouteGraph();reset();$('#routeState').textContent='출발지를 지도에서 선택하세요';}catch(error){$('#routeState').textContent='캠퍼스 지도를 불러오지 못했습니다'}}
function initReview(){if(reviewMap)return;reviewMap=L.map('reviewMap').setView(DATA.center,DATA.zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(reviewMap);reviewLayer=L.layerGroup().addTo(reviewMap);DATA.edges.forEach((e,i)=>{const line=L.polyline(e.coords.map(c=>[c[1],c[0]]),{color:'#1769e0',weight:4,opacity:.75});line.on('click',ev=>{L.DomEvent.stopPropagation(ev);line.remove();reviewRemoved.push(i);$('#reviewState').textContent='선이 삭제되었습니다. 원본은 보존됩니다.'});line.addTo(reviewLayer)});reviewMap.on('click',e=>{if(!reviewDrawing)return;reviewPoints.push([e.latlng.lng,e.latlng.lat]);L.circleMarker(e.latlng,{radius:5,color:'#ea4d61',fillOpacity:1}).addTo(reviewLayer);if(reviewPoints.length>1){const last=reviewPoints.slice(-2).map(c=>[c[1],c[0]]);L.polyline(last,{color:'#ea4d61',weight:5}).addTo(reviewLayer)}$('#reviewState').textContent=`새 선 ${reviewPoints.length}개 점`});$('#addPath').onclick=()=>{reviewDrawing=true;reviewPoints=[];$('#reviewState').textContent='지도에서 보행로 점을 클릭하세요'};$('#finishPath').onclick=()=>{if(reviewPoints.length>1){reviewAdded.push(reviewPoints.slice());$('#reviewState').textContent='새 보행로가 추가되었습니다.'}reviewDrawing=false;reviewPoints=[]};$('#reviewReset').onclick=()=>location.reload();$('#downloadReview').onclick=downloadReview}
function downloadReview(){const features=[];DATA.edges.forEach((e,i)=>{if(reviewRemoved.includes(i))return;features.push({type:'Feature',properties:{highway:e.highway,source:e.source,target:e.target,review_status:'existing'},geometry:{type:'LineString',coordinates:e.coords}})});reviewAdded.forEach((coords,i)=>features.push({type:'Feature',properties:{highway:'footway',review_status:'added',review_id:i+1},geometry:{type:'LineString',coordinates:coords}}));const blob=new Blob([JSON.stringify({type:'FeatureCollection',features},null,2)],{type:'application/geo+json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='labels_reviewed.geojson';a.click();URL.revokeObjectURL(a.href);$('#reviewState').textContent='검수본을 다운로드했습니다.'}
const startIcon=L.divIcon({className:'map-pin map-pin-start',html:'<span></span>',iconSize:[24,24],iconAnchor:[12,12]});const endIcon=L.divIcon({className:'map-pin map-pin-end',html:'<span></span>',iconSize:[24,24],iconAnchor:[12,12]});
function choose(ll){if(clicks===0){start=ll;clicks=1;L.marker(ll,{title:'출발지',icon:startIcon}).addTo(map);$('#startText').textContent=fmt(ll);$('#routeState').textContent='목적지를 지도에서 선택하세요'}else if(clicks===1){end=ll;clicks=2;L.marker(ll,{title:'목적지',icon:endIcon}).addTo(map);$('#endText').textContent=fmt(ll);showRoute()}else reset()}
function fmt(ll){return `${ll.lat.toFixed(5)}, ${ll.lng.toFixed(5)}`}
function nearest(ll){return DATA.nodes.reduce((best,n)=>{const d=(n.lat-ll.lat)**2+(n.lon-ll.lng)**2;return !best||d<best.d?{n,d}:best},null).n}
async function showRoute(){ $('#routeState').textContent='PostGIS에서 경로를 계산하는 중입니다';try{const response=await fetch(API_BASE+'/api/routes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campus_id:currentCampusId,start:{lat:start.lat,lon:start.lng},destination:{lat:end.lat,lon:end.lng}})});if(response.status===422){$('#routeState').textContent='선택한 두 지점 사이에 연결된 보행 경로가 없습니다';return}if(!response.ok)throw new Error('route api failed');const result=await response.json();if(routeLayer)routeLayer.remove();routeLayer=L.geoJSON(result.geometry,{style:{color:'#1769e0',weight:7,lineCap:'round'}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[30,30]});$('#routeResult').classList.remove('hidden');$('#routeDistance').textContent=Math.round(result.distance_m)+' m';$('#routeNodes').textContent=`${result.node_count}개 경유 노드 · PostGIS 그래프`;$('#routeState').textContent='PostGIS 경로 안내가 완료되었습니다'}catch(error){$('#routeState').textContent='API에 연결할 수 없습니다. backend를 먼저 실행하세요'}}
function reset(){clicks=0;start=end=null;map.eachLayer(l=>{if(l instanceof L.Marker)map.removeLayer(l)});if(routeLayer)routeLayer.remove();$('#startText').textContent='미지정';$('#endText').textContent='미지정';$('#routeState').textContent='출발지를 지도에서 선택하세요';$('#routeResult').classList.add('hidden')}
document.addEventListener('click',e=>{const step=e.target.closest('.step');if(!step)return;document.querySelectorAll('.before-after,.model-comparison').forEach(x=>x.classList.toggle('show',step.dataset.step==='2'))});
function loadModelComparison(){fetch('model_comparison.json').then(r=>r.json()).then(result=>{const section=document.createElement('section');section.className='model-comparison';section.innerHTML=`<div class="section-heading"><div><p class="eyebrow">MODEL BENCHMARK · SAME DATA</p><h3>기본 U-Net vs U-Net + MobileNetV3</h3><p>동일 샘플 <strong>${result.sample_id}</strong>, 동일 라벨, ${result.epochs} epoch, 검증 타일 ${result.validation_tiles}개로 실제 학습한 결과입니다.</p></div><span class="pill green">실측 비교</span></div><div class="model-compare-grid">${Object.values(result.models).map(model=>`<article><div class="card-top"><span>${model.label}</span><span class="pill">${model.seconds}초</span></div><img src="${model.overlay}" alt="${model.label} 예측 결과"><div class="benchmark-metrics"><span>Dice <strong>${model.dice}</strong></span><span>IoU <strong>${model.iou}</strong></span><span>최종 loss <strong>${model.loss_final}</strong></span></div></article>`).join('')}</div><div class="comparison-note">판정 주의: 현재 데이터는 OSM 기반 pseudo-label이며, 타일 수가 적은 파일럿 결과입니다. 모델 우열은 검수 라벨을 확대한 후 다시 확인해야 합니다.</div>`;document.querySelector('.pipeline-title').before(section)})}
setTimeout(loadModelComparison,600);
